FROM python:3.12-slim

COPY index.html /code/index.html
RUN chmod +rx /code/index.html

COPY tests.html /code/tests.html
RUN chmod +rx /code/tests.html

COPY contact.html /code/contact.html
RUN chmod +rx /code/contact.html

ENV PATH="/code:$PATH"

