version: '3'

services:
  writer:
    build:
      context: .
      dockerfile: Dockerfile-writer
    image: aekau21/writer
    volumes:
      - ./data:/data
    command: writer.py /data/data.txt

  computer:
    build:
      context: .
      dockerfile: Dockerfile-computer
    image: aekau21/computer
    volumes:
      - ./data:/data
    command: computer.py /data/data.txt /data/results.txt
